# Uncomment the next line to define a global platform for your project
platform :ios, '18.2'

target 'leetvision' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for leetvision

  target 'leetvisionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'leetvisionUITests' do
    # Pods for testing
  end
end
