# Uncomment the next line to define a global platform for your project
platform :ios, '18.2'
use_frameworks!

target 'leetvision' do
  # Pods for leetvision
  pod 'HighlightSwift'

  target 'leetvisionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'leetvisionUITests' do
    # Pods for testing
  end
end
