package org.leetvision.parser.meta;

public final class MetaLanguage {
    private MetaLanguage() {
    }

    public enum MetaNode {
        PROGRAM,
        IMPORT,

        TYPE_DECLARATION,
        MODIFIER,
        CLASS_MODIFIER,
        VARIABLE_MODIFIER,
        CLASS_DECLARATION,
        TYPE_PARAMETERS,
        TYPE_PARAMETER,
        UNION_TYPE,

        ENUM_DECLARATION,
        ENUM_CONSTANTS,
        ENUM_CONSTANT,
        ENUM_BODY_DECLARATIONS,

        INTERFACE_DECLARATION,
        CLASS_BODY,
        INTERFACE_BODY,
        BODY_DECLARATION,
        MEMBER_DECLARATION,
        METHOD_DECLARATION,
        METHOD_BODY,

        TYPE,
        CLASS_OR_INTERFACE_TYPE,
        TYPE_IDENTIFIER,
        TYPE_PRIMITIVE,
        TYPE_ARGUMENTS,

        QUALIFIED_NAME_LIST,
        QUALIFIED_NAME,
        FORMAL_PARAMETERS,
        FORMAL_PARAMETER,
        LAMBDA_PARAMETERS,
        LAMBDA_PARAMETER,

        CONSTRUCTOR_DECLARATION,
        FIELD_DECLARATION,
        CONST_DECLARATION,
        CONSTANT_DECLARATOR,
        INTERFACE_METHOD_MODIFIER,

        VARIABLE_DECLARATORS,
        VARIABLE_DECLARATOR,
        VARIABLE_INITIALIZER,
        ARRAY_INITIALIZER,

        EXPRESSION_VALUE_PAIRS,
        EXPRESSION_VALUE_PAIR,
        EXPRESSION_VALUE_ARRAY_INITIALIZER,

        DEFAULT_VALUE,
        RECORD_DECLARATION,
        RECORD_HEADER,
        RECORD_COMPONENT_LIST,
        RECORD_COMPONENT,
        RECORD_BODY,

        BLOCK,
        LOCAL_VARIABLE_DECLARATION,
        IDENTIFIER,
        STATEMENT,

        CATCH_CLAUSE,
        CATCH_TYPE,
        FINALLY_BLOCK,
        TRY_RESOURCE_SPECIFIER,
        TRY_RESOURCES,
        TRY_RESOURCE,

        SWITCH_BLOCK_STATEMENT_GROUP,
        SWITCH_LABEL,
        FOR_CONTROL,
        FOR_INIT,
        FOREACH_CONTROL,
        EXPRESSION_LIST,
        METHOD_CALL,
        EXPRESSION,
        PATTERN,
        GUARDED_PATTERN,
        LAMBDA_EXPRESSION,
        LAMBDA_BODY,
        SWITCH_EXPRESSION,
        SWITCH_LABELED_RULE,
        SWITCH_RULE_OUTCOME,
        CLASS_TYPE,

        CREATOR,
        CREATED_NAME,
        INNER_CREATOR,
        ARRAY_CREATOR_REST,
        CLASS_CREATOR_REST,

        EXPLICIT_GENERIC_INVOCATION,
        TYPE_LIST,
        SUPER_SUFFIX,
        EXPLICIT_GENERIC_INVOCATION_SUFFIX,
        ARGUMENTS,

        // terminals

        DECIMAL_LITERAL,
        HEX_LITERAL,
        OCT_LITERAL,
        BINARY_LITERAL,
        FLOAT_LITERAL,
        HEX_FLOAT_LITERAL,
        BOOL_LITERAL,
        CHAR_LITERAL,
        STRING_LITERAL,
        MULTILINE_STRING_LITERAL,
        NULL_LITERAL,

        MODIFIER_ABSTRACT,
        MODIFIER_CONST,
        MODIFIER_EXTENDS,
        MODIFIER_IMPLEMENTS,
        MODIFIER_FINAL,
        MODIFIER_NATIVE,  // ?
        MODIFIER_PRIVATE,
        MODIFIER_PROTECTED,
        MODIFIER_PUBLIC,
        MODIFIER_STATIC,
        MODIFIER_STRICTFP,  // ?
        MODIFIER_SYNCHRONIZED,
        MODIFIER_THROWS,
        MODIFIER_TRANSIENT,
        MODIFIER_VOLATILE,
        MODIFIER_SEALED,
        MODIFIER_VARARGS,  // ...

        STATEMENT_ASSERT,
        STATEMENT_BREAK,
        STATEMENT_CONTINUE,
        STATEMENT_SWITCH,
        STATEMENT_CASE,
        STATEMENT_DEFAULT,
        STATEMENT_TRY,
        STATEMENT_CATCH,
        STATEMENT_DO,
        STATEMENT_ELSE,
        STATEMENT_FINALLY,
        STATEMENT_FOR,
        STATEMENT_IF,
        STATEMENT_GOTO,
        STATEMENT_RETURN,
        STATEMENT_THROW,
        STATEMENT_WHILE,
        STATEMENT_YIELD,

        EXPR_INSTANCEOF,
        EXPR_NEW,
        EXPR_SUPER,
        EXPR_THIS,

        OP_ASSIGN,
        OP_ADD_ASSIGN,
        OP_SUB_ASSIGN,
        OP_MUL_ASSIGN,
        OP_DIV_ASSIGN,
        OP_AND_ASSIGN,
        OP_OR_ASSIGN,
        OP_XOR_ASSIGN,
        OP_MOD_ASSIGN,
        OP_LSHIFT_ASSIGN,
        OP_RSHIFT_ASSIGN,
        OP_URSHIFT_ASSIGN,
        OP_GT,
        OP_LT,
        OP_NOT,
        OP_BITNOT,
        OP_TERNARY,
        OP_EQUAL,
        OP_LE,
        OP_GE,
        OP_NOTEQUAL,
        OP_AND,
        OP_OR,
        OP_XOR,
        OP_INC,
        OP_DEC,
        OP_ADD,
        OP_SUB,
        OP_MUL,
        OP_DIV,
        OP_MOD,
        OP_BITAND,
        OP_BITOR,
        OP_LAMBDA,
        OP_METHOD_REFERENCE,  // ::

        TYPE_BOOLEAN,
        TYPE_BYTE,
        TYPE_CHAR,
        TYPE_CLASS,
        TYPE_INTERFACE,
        TYPE_DOUBLE,
        TYPE_ENUM,
        TYPE_FLOAT,
        TYPE_INT,
        TYPE_LONG,
        TYPE_SHORT,
        TYPE_VOID,
        TYPE_VAR,
        TYPE_RECORD,

        // hacks - concrete but similar enough between all languages
        L_SQUARE,
        R_SQUARE,
        DOT,
        COMMA
    }
}
